name: deploy-chart
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      service:
        type: string
        required: true
    secrets:
      GH_ORG_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: release

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: property-xyz-v2/platform-stage-cluster-argo
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Update chart version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.helmCharts[0].version= "${{ inputs.version }}"' apps/staging-env/apps/${{ inputs.service }}/kustomization.yaml

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          commit-message: >-
            chore: promote ${{ inputs.service }} to version  $${{ inputs.version }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: pr-${{ inputs.service }}-${{ inputs.version }}
          delete-branch: true
          signoff: false
          title: Promote ${{ inputs.service }} to version v${{ inputs.version }}
          labels: |
            automated pr