name: quarkus-build
on:
  workflow_call:
    inputs:
      isNative:
        type: boolean
        required: true
    outputs:
      version:
        description: "The artifacts next version"
        value: ${{ jobs.build.outputs.version }}
      tag:
        description: "The artifacts next tag"
        value: ${{ jobs.build.outputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.tag_version.outputs.new_version }}
      tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: 'maven'

      - name: Build application
        run: |
          ./mvnw  versions:set -DnewVersion=${{ steps.tag_version.outputs.new_version }}
          if [[ ${{ inputs.isNative }} = true ]]; then
           ./mvnw clean package -Dnative -Dquarkus.native.container-build=true
          else
           ./mvnw clean package
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: built-application
          path: target/