name: deploy-chart
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      GH_ORG_TOKEN:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        environment:
          - staging
          - production

    steps:
      - name: print version
        run: echo ${{ inputs.version }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: property-xyz-v2/platform-stage-cluster-argo
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Update chart version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.helmCharts[0].version= "${{ inputs.version }}"' apps/${{ matrix.environment }}-env/apps/${{ github.event.repository.name }}/kustomization.yaml

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          title: Promote ${{ github.event.repository.name }} to version v${{ inputs.version }}
          commit-message: >-
            chore: promote ${{ github.event.repository.name }} to version v${{ inputs.version }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: pr-${{ github.event.repository.name }}-${{ inputs.version }}
          delete-branch: true
          signoff: false
          labels: |
            automated pr