name: deploy-chart
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      namespace:
        type: string
        required: false
    secrets:
      GH_ORG_TOKEN:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - stage
          - production

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: property-xyz/linode-platform-${{ matrix.environment }}-cluster-argo
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Update chart version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.helmCharts[0].version= "${{ inputs.version }}"' apps/${{ inputs.namespace || matrix.environment }}/apps/${{ github.event.repository.name }}/kustomization.yaml

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          title: Promote ${{ github.event.repository.name }} to version v${{ inputs.version }}
          commit-message: >-
            chore: promote ${{ github.event.repository.name }} to version v${{ inputs.version }}
          committer: GitHub <noreply@github.com>
          author: property-xyz-bot <security@property.xyz>
          branch: pr-${{ github.event.repository.name }}-${{ inputs.version }}
          delete-branch: true
          signoff: false
          labels: |
            automated pr
