name: release-image
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      dockerFile_path:
        type: string
        required: false
      registry:
        type: string
        default: 'ghcr.io'
        required: false
      registry_username:
        type: string
        default: 'property-xyz-bot'
        required: false
jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_username }}
          password: ${{ secrets.XYZ_BOT_TOKEN }}

      - name: Set Docker file path
        run: echo "DOCKERFILE_PATH=${{ inputs.dockerFile_path }}" >> $GITHUB_ENV

      - name: Create a .npmrc file for the github private repository
        uses: FerLuisxd/create-npmrc@master
        with:
          org_name: property-xyz
          auth_token: ${{ secrets.GH_ORG_TOKEN }}
          
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          file_name: .env.local
          envkey_NEXT_PUBLIC_XYZ_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_XYZ_GOOGLE_MAPS_API_KEY }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ inputs.registry }}/${{ github.repository }}:${{ inputs.tag }}
