name: release-image
on:
  workflow_call:
    inputs:
      registry:
        type: string
        default: 'ghcr.io'
        required: false
      registry_username:
        type: string
        default: 'property-xyz-bot'
        required: false
    outputs:
      version:
        description: "The artifacts next version"
        value: ${{ jobs.release.outputs.version }}
      tag:
        description: "The artifacts next tag"
        value: ${{ jobs.release.outputs.tag }}
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bumper.outputs.new_version }}
      tag: ${{ inputs.registry }}/${{ github.repository }}:${{ steps.bumper.outputs.new_version }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run bumper
        id: bumper
        uses: tomerfi/version-bumper-action@1.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_username }}
          password: ${{ secrets.XYZ_BOT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ inputs.registry }}/${{ github.repository }}:${{ steps.bumper.outputs.new_version }}