name: release-image
on:
  workflow_call:
    inputs:
      registry:
        type: string
        default: 'ghcr.io'
        required: false
      registry_username:
        type: string
        default: 'property-xyz-bot'
        required: false
    outputs:
      version:
        description: "The artifacts next version"
        value: ${{ jobs.release.outputs.version }}
      tag:
        description: "The artifacts next tag"
        value: ${{ jobs.release.outputs.tag }}
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag_version.outputs.new_version  }}
      tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint code
        uses: chartboost/ruff-action@v1
        with:
          version: 0.0.292
          src: 'src test'

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_username }}
          password: ${{ secrets.XYZ_BOT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ inputs.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}
