name: quality-assurance
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.11'
        required: false
      pdm-version:
        type: string
        default: '2.10.0'
        required: false
      ruff-version:
        type: string
        default: '0.1.3'
        required: false
      test-folder:
        type: string
        default: 'test/unit'
        required: false
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ inputs.python-version }}
          version: ${{ inputs.pdm-version }}
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Create a .npmrc file for the github private repository
        uses: FerLuisxd/create-npmrc@master
        with:
          org_name: property-xyz
          auth_token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Install npm dependencies
        run: npm install

      - name: Lint code
        uses: chartboost/ruff-action@v1
        with:
          version: ${{ inputs.ruff-version }}
          src: 'src test'

      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: true
          job-summary: true
          custom-pytest: pdm run pytest ${{ inputs.test-folder }}
