name: release-image-helm
on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true
      version:
        type: string
        required: true
      tag:
        type: string
        required: true
      registry:
        type: string
        required: true
    secrets:
      GH_ORG_TOKEN:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: built-application
          path: target/quarkus-app

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{  inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ inputs.registry }}/${{ inputs.service_name }}:${{ inputs.tag }}

      - name: Update image tag in helm values
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = "${{ inputs.tag }}"' charts/${{ inputs.service_name }}/values.yaml

      - name: Update version in helm chart
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ inputs.version }}"' charts/${{ inputs.service_name }}/Chart.yaml

      - name: Release helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          repository: platform-helm-charts
          token: ${{ secrets.GH_ORG_TOKEN }}
          charts_url: https://property-xyz.github.io/platform-helm-charts/
